### ISSUE TITLE
Incorrect syntax for example workflow

### ISSUE THREAD

**Issue by cfbender** [connor-baer/action-sync-branch#66]
Hi there!

Thanks for making this action. Noticed a slight error in the example workflow syntax, it should be: 

```
on:
  push:
    branches:
      - main
```

The `branches` key is necessary for the filter.
